"""Read File Tool - Read local file content with security restrictions and sensitive file protection."""
from pathlib import Path

from langchain_core.tools import tool
from config import PROJECT_ROOT, settings
from security.classifier import classify_file_path, RiskLevel


@tool
def read_file(file_path: str) -> str:
    """Read the content of a local file.

    This tool reads files within the data directory or the project source directory.
    It is commonly used to read SKILL.md files for learning new skills, or to read
    memory/config files, or files generated by other tools.

    Args:
        file_path: Path to the file to read (relative path or absolute).
                   Relative paths are resolved against data directory first, then project root.

    Returns:
        The content of the file, or an error message.
    """
    try:
        path = Path(file_path)
        data_path = settings.get_data_path()

        # If relative, try data_dir first, then project root
        if not path.is_absolute():
            data_resolved = (data_path / path).resolve()
            proj_path = (PROJECT_ROOT / path).resolve()
            if data_resolved.exists():
                path = data_resolved
            else:
                path = proj_path
        else:
            path = path.resolve()

        # Security check: must be within data_dir OR project root
        in_project = False
        in_data = False
        try:
            path.relative_to(PROJECT_ROOT)
            in_project = True
        except ValueError:
            pass
        try:
            path.relative_to(data_path)
            in_data = True
        except ValueError:
            pass

        if not in_project and not in_data:
            return f"❌ Error: Access denied. Cannot read files outside the data directory or project: {path}"

        # Sensitive file protection (hard-block .env, keys, credentials)
        try:
            from config import settings
            sensitive_on = settings.security_enabled and settings.security_sensitive_file_protection
        except Exception:
            sensitive_on = True
        if sensitive_on:
            risk = classify_file_path(str(path))
            if risk == RiskLevel.BLOCKED:
                return f"⛔ Blocked: Cannot read sensitive file: {path.name}"

        if not path.exists():
            return f"❌ Error: File not found: {file_path}"

        if not path.is_file():
            return f"❌ Error: Path is not a file: {file_path}"

        content = path.read_text(encoding="utf-8")

        # Limit output for very large files
        if len(content) > 20000:
            content = content[:20000] + "\n\n...[file content truncated at 20000 chars]"

        return content

    except UnicodeDecodeError:
        return f"❌ Error: File is not a text file or has encoding issues: {file_path}"
    except Exception as e:
        return f"❌ Error reading file: {str(e)}"


def create_read_file_tool():
    """Factory function to create the read_file tool."""
    return read_file
